# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-09 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('validation_goal', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('campaigns', models.ManyToManyField(to='voter_validation.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('campaign_pk', models.IntegerField()),
                ('voter_full_name', models.CharField(default='', max_length=100)),
                ('voter_res_address', models.CharField(default='', max_length=70)),
                ('voter_uid', models.CharField(default='', max_length=60)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voter_validation.Campaign')),
                ('validator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voter_validation.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voter_id', models.CharField(default='', max_length=60, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, default='', max_length=32)),
                ('middle_name', models.CharField(db_index=True, default='', max_length=32)),
                ('last_name', models.CharField(db_index=True, default='', max_length=32)),
                ('suffix', models.CharField(default='', max_length=32)),
                ('res_addr', models.CharField(db_index=True, default='', max_length=70)),
                ('res_addr_zip', models.CharField(db_index=True, default='', max_length=10)),
                ('res_addr_city', models.CharField(default='', max_length=30)),
                ('res_addr_state', models.CharField(default='', max_length=2)),
                ('res_addr_house_num', models.CharField(default='', max_length=10)),
                ('res_addr_street_name', models.CharField(default='', max_length=35)),
                ('res_addr_street_suff', models.CharField(default='', max_length=10)),
                ('res_addr_unit_num', models.CharField(default='', max_length=8)),
                ('phone', models.CharField(default='', max_length=14)),
                ('email', models.CharField(default='', max_length=100)),
                ('curr_reg_date', models.CharField(default='', max_length=10)),
                ('orig_reg_date', models.CharField(default='', max_length=10)),
                ('reg_status', models.CharField(choices=[('A', 'Active'), ('C', 'Cancelled'), ('I', 'Inactive'), ('P', 'Local Pending'), ('', 'None')], db_index=True, default='', max_length=1)),
                ('reg_status_reason', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=1)),
                ('party', models.CharField(default='', max_length=50)),
                ('language', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='validationrecord',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voter_validation.Voter'),
        ),
        migrations.AlterUniqueTogether(
            name='validationrecord',
            unique_together=set([('campaign_pk', 'voter_uid')]),
        ),
    ]
