# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-13 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrecord',
            name='campaign_pk',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='validationrecord',
            name='voter_full_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='validationrecord',
            name='voter_res_address',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='validationrecord',
            name='voter_uid',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
