# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-14 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_validation', '0003_auto_20180513_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='res_addr_zip',
            field=models.CharField(db_index=True, default='', max_length=5),
        ),
    ]
